/**
 * Generated by `./scripts/prebuild/generate-icons.ts`.
 * Run `yarn generate-icons` to regenerate.
 */

import React from 'react';
import { findClosestGlyphAvailable, Icon } from '../../';
export function IconRadio(props) {
  var _props$autoMirror;
  /* prettier-ignore */
  var iconList = [{
    'size': 16,
    'svgContent': '<path d=\'M5.624 3.886A4.748 4.748 0 0 0 3.25 8c0 1.758.955 3.293 2.375 4.114l.75-1.3a3.249 3.249 0 0 1 0-5.63l-.75-1.298zm4.001 1.299.75-1.3A4.748 4.748 0 0 1 12.75 8a4.748 4.748 0 0 1-2.375 4.114l-.75-1.3a3.249 3.249 0 0 0 0-5.63zM8 6.545a1.455 1.455 0 1 0 0 2.91 1.455 1.455 0 0 0 0-2.91z\'/><path d=\'M4 1.07A7.997 7.997 0 0 0 0 8a7.997 7.997 0 0 0 4 6.93l.75-1.3A6.497 6.497 0 0 1 1.5 8a6.497 6.497 0 0 1 3.25-5.63L4 1.07zm7.25 1.3.75-1.3A7.997 7.997 0 0 1 16 8a7.997 7.997 0 0 1-3.999 6.93l-.75-1.3A6.497 6.497 0 0 0 14.5 8a6.497 6.497 0 0 0-3.25-5.63z\'/>'
  }, {
    'size': 24,
    'svgContent': '<path d=\'M8.75 6.37A6.497 6.497 0 0 0 5.5 12a6.497 6.497 0 0 0 3.25 5.63l1-1.732A4.498 4.498 0 0 1 7.5 12a4.5 4.5 0 0 1 2.25-3.898l-1-1.732zm5.5 1.732 1-1.732A6.497 6.497 0 0 1 18.5 12a6.497 6.497 0 0 1-3.25 5.63l-1-1.732A4.498 4.498 0 0 0 16.5 12a4.5 4.5 0 0 0-2.25-3.898zM12 10a2 2 0 1 0 0 4 2 2 0 0 0 0-4z\'/><path d=\'M6.499 2.472A10.996 10.996 0 0 0 1 12c0 4.071 2.212 7.626 5.499 9.528l1-1.732A8.997 8.997 0 0 1 3 12c0-3.33 1.81-6.24 4.5-7.795L6.498 2.472zm10.002 1.732 1-1.732A10.996 10.996 0 0 1 23 12c0 4.071-2.212 7.626-5.499 9.528l-1-1.732A8.996 8.996 0 0 0 21 12c0-3.33-1.81-6.24-4.5-7.796z\'/>'
  }];
  var closestSize = findClosestGlyphAvailable(iconList, props.iconSize || 24);
  var titleTag = function titleTag(title, titleId) {
    return title ? '<title '.concat(titleId ? 'id="'.concat(titleId, '"') : '', '>').concat(title, '</title>') : '';
  };
  var descTag = function descTag(desc, descId) {
    return desc ? '<desc '.concat(descId ? 'id="'.concat(descId, '"') : '', '>').concat(desc, '</desc>') : '';
  };
  var autoMirror =
    (_props$autoMirror = props.autoMirror) !== null && _props$autoMirror !== void 0 ? _props$autoMirror : false;
  return /*#__PURE__*/ React.createElement(
    Icon,
    Object.assign({}, props, {
      autoMirror: autoMirror,
      viewBox: '0 0 '.concat(closestSize.size, ' ').concat(closestSize.size),
      dangerouslySetInnerHTML: {
        __html: ''
          .concat(titleTag(props.title, props.titleId))
          .concat(descTag(props.desc, props.descId))
          .concat(closestSize.svgContent),
      },
    }),
  );
}

/**
 * @deprecated The name Experimental__IconRadio is deprecated and will be archived soon. Use IconRadio instead.
 */
export function Experimental__IconRadio(props) {
  return /*#__PURE__*/ React.createElement(IconRadio, props);
}
